In [6]:
(-25)%7

3

In [2]:
5 // 2

2

In [3]:
2 // 2

1

In [4]:
3 // 2

1

In [5]:
array1 = [2, 3, 5, 7, 9]
newarray = array1[2:]
newarray[4]

IndexError: list index out of range

In [6]:
8//2

4

In [7]:
array1 = [2, 3, 5, 7, 9, 10, 15, 18, 22, 27, 30, 32]

In [8]:
len(array1)

12

In [9]:
len(array1) // 2

6

In [10]:
array1[6]

15

In [11]:
10 // 2

5

In [12]:
5 // 2

2

In [16]:
(5 - 2) // 2

1

In [17]:
(5-3) // 2

1

In [9]:
import numpy as np
array1 = np.random.rand(5,4)
print(array1)

[[0.41677276 0.85757995 0.43321401 0.41633735]
 [0.38461764 0.11974225 0.14515707 0.29755736]
 [0.45122547 0.23428081 0.95562652 0.62728712]
 [0.8021967  0.42498903 0.10852444 0.34758337]
 [0.89214471 0.75951891 0.69222378 0.32207643]]


In [11]:
# array1 = np.random.rand(5,4)
array1[0][1]

0.8575799450017773

In [15]:
array1.shape[1]

4

In [16]:
np.zeros(array1.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
0x2a

42

In [18]:
empty = list()
empty[3] = 2
empty

IndexError: list assignment index out of range

In [20]:
2**63

9223372036854775808

In [22]:
hex(0xffff + 1)

'0x10000'

In [23]:
sqrt(2)

NameError: name 'sqrt' is not defined

In [29]:
import math
math.sqrt(5)

2.23606797749979

In [26]:
0x6a09e667

1779033703

In [27]:
0x5be0cd19

1541459225

In [30]:
0x1f83d9ab

528734635

In [32]:
coinlist = [1, 2, 5]
coinlist.reverse()
coinlist

[5, 2, 1]

In [33]:
len(coinlist)

3

In [45]:
def change_list(list1):
    list1.append(7)
    # return list1

In [46]:
def call_fn(list1):
    change_list(list1)
    # return list1

In [49]:
list1 = [1,2,3]
call_fn(list1)
print(list1)

[1, 2, 3, 7]


In [50]:
list1.pop()
list1.pop()
list1

[1, 2]

In [54]:
list2 = [1,2]
list3 = list2
list4 = list2[:]
list5 = []
list5.append(list2[:])
list5.append(list2)
list2.pop()
print(list3)
print(list4)
print(list5)

[1]
[1, 2]
[[1, 2], [1]]


In [55]:
list5 = []
list5.append(list2[:])

In [57]:
amount = 7
solution = [0] * (amount + 1)
solution

[0, 0, 0, 0, 0, 0, 0, 0]

In [61]:
def solve_coin_change(denominations, amount):
  solution = [0] * (amount + 1)
  solution[0] = 1;
  for den in denominations:
    print(f"den: {den}")
    for i in range(den, amount + 1):
      print(f"i: {i}")
      solution[i] += solution[i - den] 
      print(f"[i-den]: {[i-den]}")
      print(solution)

  return solution[len(solution) - 1]
    
denominations = [1, 2, 5]
amount = 7
result = solve_coin_change(denominations, amount)
# printing the answer
print("solve_coin_change(" + str(denominations) + ', ' + str(amount) + ') = ', end = '' )
print(result)

den: 1
i: 1
[i-den]: [0]
[1, 1, 0, 0, 0, 0, 0, 0]
i: 2
[i-den]: [1]
[1, 1, 1, 0, 0, 0, 0, 0]
i: 3
[i-den]: [2]
[1, 1, 1, 1, 0, 0, 0, 0]
i: 4
[i-den]: [3]
[1, 1, 1, 1, 1, 0, 0, 0]
i: 5
[i-den]: [4]
[1, 1, 1, 1, 1, 1, 0, 0]
i: 6
[i-den]: [5]
[1, 1, 1, 1, 1, 1, 1, 0]
i: 7
[i-den]: [6]
[1, 1, 1, 1, 1, 1, 1, 1]
den: 2
i: 2
[i-den]: [0]
[1, 1, 2, 1, 1, 1, 1, 1]
i: 3
[i-den]: [1]
[1, 1, 2, 2, 1, 1, 1, 1]
i: 4
[i-den]: [2]
[1, 1, 2, 2, 3, 1, 1, 1]
i: 5
[i-den]: [3]
[1, 1, 2, 2, 3, 3, 1, 1]
i: 6
[i-den]: [4]
[1, 1, 2, 2, 3, 3, 4, 1]
i: 7
[i-den]: [5]
[1, 1, 2, 2, 3, 3, 4, 4]
den: 5
i: 5
[i-den]: [0]
[1, 1, 2, 2, 3, 4, 4, 4]
i: 6
[i-den]: [1]
[1, 1, 2, 2, 3, 4, 5, 4]
i: 7
[i-den]: [2]
[1, 1, 2, 2, 3, 4, 5, 6]
solve_coin_change([1, 2, 5], 7) = 6


In [64]:
checknull = [0,-2,None]

In [65]:
len(checknull)

3

In [66]:
max(checknull)

TypeError: '>' not supported between instances of 'NoneType' and 'int'

In [91]:
diction = [1, "a", [76, "b"]]

In [69]:
diction[0]

1

In [92]:
diction[2]

[76, 'b']

In [93]:
dic = [None] * 100

def set_entry(entry):
    '''Set an entry in dictionary'''
    string = str(entry)
    key = 0
    for letter in string:
        key += ord(letter)
    

ord("a")

97

In [73]:
chr(97)

'a'

In [74]:
chr(0)

'\x00'

In [75]:
chr(1)

'\x01'

In [88]:
chr(10)
chr(12)
chr(15)
chr(16)
chr(17)
chr(82)
chr(50)
chr(47)
chr(40)

'('

In [89]:
ord("howdy")

TypeError: ord() expected a character, but string of length 5 found

In [90]:
[None] * 10

[None, None, None, None, None, None, None, None, None, None]

In [1]:
arr1 = [1,2,3,4,5,6]
arr1[:3]

[1, 2, 3]

In [2]:
arr2 = arr1[3:] + arr1[:3]
arr2

[4, 5, 6, 1, 2, 3]

In [3]:
2 % 6

2

In [5]:
arr3 = arr1[-2:] + arr1[:-2]
arr3

[5, 6, 1, 2, 3, 4]

In [14]:
arr4 = arr1[4:] + arr1[:4]
arr4

[5, 6, 1, 2, 3, 4]

In [13]:
-2 % 6

4

In [9]:
-14 % -6

-2

In [10]:
-2 // 6

-1

In [11]:
2 // 6

0